### ISSUE TITLE
How to pass Zap report to SonarQube

### ISSUE THREAD

**Issue by yantantether** [pdsoftplan/sonar-zap#1]
This is probably an issue with my usage, but I can't work out how to get Maven to send the Zap report in to SonarQube for analysis.
- I am using your zap-maven-plugin to run an analysis and this is working correctly, generating html and xml zap reports on my build server. 
- I am then calling the sonar-maven-plugin with sonar:sonar to send the report across to SonarQube. This has worked previously with unit test results, Jacoco code coverage and Sonar static file analysis. 
- But I am getting nothing Zap related in SonarQube.
- I think I have the Zap plugin installed correctly in SonarQube as I can see the config section.

My maven call looks like this:

```
mvn -X -B -Pzap -DzapPort=$ZAP_PORT -DzapHost=$ZAP_HOST -DzapTargetUrl=http://idpapp00:8080/sample-webapp/ -DsonarUrl=$SONAR_URL  -Dsonar.branch=$CI_BUILD_REF_NAME br.com.softplan.security.zap:zap-maven-plugin:analyze sonar:sonar
```

Can you tell me how I should be sending the Zap report across to sonarqube?

**Comment by tfcporciuncula** [comment]
Thank you for your feedback! Any suggestions and questions you might have are certainly welcome.

First of all, we should make sure the plugin is running. Try invoking only SonarQube (by running `sonar:sonar`) and check its log. Look for any line that mentions the `ZapSensor` or ZAP itself.

If the plugin is correctly installed, it will run no matter what every time you run an analysis on SonarQube, and it will at least print something like: `ZAP report not found at some/folder`. This could actually give you a clue of what's wrong (maybe the report is not where it should be?).

Let me know if you need any more help.

**Comment by yantantether** [comment]
Hi Thiago, thanks for your response.
Actually I think it is all working: I added a quality gate and made our build fail. I also added the Zap alert column to the _measures_ grid and saw 9 alerts.
I think my problem is that although I can see we have alerts, the integration with Sonar is pretty basic, so:
-  I can't se an overview of alerts under the _project home_ view
- There doesn't seem to be a way to see the actual alerts: i.e. what is wrong. Perhaps that needs integration with the Issues API?

Is that simply because this is a new plugin, and its work in progress?

**Comment by tfcporciuncula** [comment]
You should be able to see an overview of the alerts under the _project home_ by clicking on `Configure widgets` and adding the ZAP widget. You have to manually add it.

The integration we did with SonarQube was actually that simple. The plugin just keeps track of the number of the alerts and that's about it. We've stopped working to improve the integration because at the time we were writing the plugin, a more complete plugin came out. It treats the ZAP's alerts as regular issues and you can actually see information about each alert identified. You should probably try it!

https://github.com/stevespringett/zap-sonar-plugin

**Comment by yantantether** [comment]
Hi Thiago, thanks for clarifying about the widget... that works fine.
And thanks for pointing me to the other sonar zap plugin. It works really well.

**Comment by digitalhuman** [comment]
Well I can tell you, the Sonar Zap Plugin doesn't work either so. Don't bother.

**Comment by dantemorius** [comment]
Hi,

I have a similar problem, with output "ZAP report not found at some/folder" but the report is there...can you help me?

I tried with xml report and html, but no matter what folder i put the report into, the error is the same. Is there any configuration to be made in the SonarQube to bind the report/plugin to the project? I'm using SonarQube as a Docker container into my "DevOps Tools", not the Jenkins plugin.
