### ISSUE TITLE
SONAR ZAP 

### ISSUE THREAD

**Issue by FcoSanchezDelRosario** [pdsoftplan/sonar-zap#3]

**Comment by fabiusks** [comment]
@FranciscoSan hello Francisco. Sorry for answering so lately! Have you solved your issue by yourself? Thanks for your time for giving us feedback and always feel welcome to post issues :)

**Comment by FcoSanchezDelRosario** [comment]
Hello @fabiusks . Thank much for answering. I was able to resolve the issue
